server:
    port: 8080

spring:
    application:
        name: holddie-mybatis
    datasource:
        primary:
            driver-class-name: com.mysql.jdbc.Driver
            password: admin123
            url: jdbc:mysql://10.20.69.237:3306/maven-demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
            username: admin
        secondary:
            driver-class-name: com.mysql.jdbc.Driver
            password: admin123
            url: jdbc:mysql://10.20.69.237:3306/maven-demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
            username: admin

redis:
    cluster:
        nodes: ''
    config:
        restAppid: 10001
        restClientVersion: 1.0-SNAPSHOT
        restUrl: http://10.20.69.237:8585
        type: rest
    host: 127.0.0.1
    maxIdle: 500
    maxTotal: 500
    maxWaitMillis: -1
    password: ''
    port: 6379
    sentinel:
        master: ''
        nodes: ''
    type: cluster


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.holddie.springboot.mybatis.*.entity
  #typeEnumsPackage: com.holddie.springboot.mybatis.rest.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #mp2.3+ 全局表前缀 mp_
    # table-prefix: mp_
    #数据库大写下划线转换
    # capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    meta-object-handler: com.holddie.springboot.mybatis.config.mybatis.MyBatisMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
logging:
  level:
    com.holddie.springboot: debug
debug: true